import { defineConfig } from 'astro/config';

// Sitemaps are generated by scripts/build-sitemaps.mjs (split by depth tier
// per brief §6.4 / §8) rather than @astrojs/sitemap, which cannot split.
export default defineConfig({
  site: 'https://inklinenews.com',
  trailingSlash: 'always',
  build: { format: 'directory' },
  compressHTML: true,
});
